#!/usr/bin/env bash
set -e

IMG=build/uefi.img
SIZE_MB=64
MOUNT=build/uefi
KERNEL=build/kernel/kernel.elf

if (( EUID != 0 )); then
	cat <<-EOF
	ERROR: You must run this script as root.
	EOF
	exit 1
fi

if [[ ! -f $KERNEL ]]; then
	cat <<-EOF
	ERROR: $KERNEL is missing. Compiler this project first.
	EOF
	exit 1
fi

rm -f $IMG
rm -rf $MOUNT
mkdir -p $MOUNT

dd if=/dev/zero of=$IMG bs=1M count=$SIZE_MB status=none
chmod 666 $IMG
mkfs.fat -F32 $IMG >/dev/null
mount $IMG $MOUNT

mkdir -p $MOUNT/EFI/BOOT
mkdir -p $MOUNT/boot/grub

cp $KERNEL $MOUNT/boot/kernel.elf

cat <<'EOF' > $MOUNT/boot/grub/grub.cfg
set timeout=3
set default=0

menuentry "Hugo OS (Multiboot2)" {
    search --file --set=root /boot/kernel.elf
    multiboot2 /boot/kernel.elf
    boot
}
EOF

grub2-mkstandalone \
    -O x86_64-efi \
    -o BOOTX64.EFI \
    "boot/grub/grub.cfg=$MOUNT/boot/grub/grub.cfg"

mv BOOTX64.EFI $MOUNT/EFI/BOOT/

umount $MOUNT
rmdir $MOUNT

cat <<EOF
UEFI image created: $IMG

Write to USB with:

    sudo dd if=$IMG of=/dev/sdX bs=4M status=progress conv=fsync

EOF
